name: PSScript checker

on:
  push:
    paths:
      - '**.ps1'
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout
      uses: actions/checkout@v3

    - name: Run PSScriptAnalyzer
      uses: microsoft/psscriptanalyzer-action@v1.0
      with:
        path: .\installer
        recurse: true 
        includeDefaultRules: true 
        enableExit: true
